name: Publish Java SDK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish-sdk:
    runs-on: ubuntu-latest

    steps:
     - name: Make new directory
       run: mkdir spec
       
    #  - name: Checkout main branch
    #    uses: actions/checkout@v2
    #    with:
    #     repository: 'apimatic/apimatic-api-docs'
    #     ref: 'main'
    #     token: ${{ secrets.ACTIONS_PAT }}
    #     path: 'api-docs'
     
     - name: Install zip
       uses: montudor/action-zip@v0.1.1
      
     - uses: actions/checkout@v1
       name : checkout-repo
       id: checkout-repo  

    #  - name: Copy spec folder to current directory
    #    run: 'cp -r -f -a ./api-docs/spec ./spec'

     - name: Zip API spec
       working-directory: 'spec'
       run: zip -qq -r api-spec.zip .
    
     - name: Generate SDK
       working-directory: 'spec'
       run: curl -X POST --url 'https://www.apimatic.io/api/code-generations/generate-via-file' -H 'Accept:application/json' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@api-spec.zip'  -F 'template=JAVA_ECLIPSE_JRE_LIB' -o java-sdk.zip
    
     - name: Check-out static-portal-sdk repo
       uses: actions/checkout@v2
       with:
        repository: 'apimatic/static-portal-sdk'
        ref: 'master'
        token: ${{secrets.ACTIONS_PAT}}
        path: 'sdk'
          
     - name: Extract generated SDK
       working-directory: 'spec'
       run: unzip -qq java-sdk.zip -d java-sdk
    
     - name: Copy SDK files
       working-directory: 'spec/java-sdk/Apimatic API'
       run: cp -r -f -a . ../../../sdk --verbose
      
     - name: Push updated SDK
       working-directory: 'sdk'
       run: |
         git add .
         git config --global user.name 'sohaibtariq'
         git config --global user.email 'sohaib.tariq@apimatic.com'
         git commit -m "updated via github CI"
         git push origin main     